[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]

remappings = [
  "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts"
]

[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
holesky="https://eth-holesky.g.alchemy.com/v2/7jl_hPvjjEmayZTegWpMuRt-tkVDjV7t"

